### PR TITLE
Migration to express.js

### PR DESCRIPTION
**Pull request by andreszorro**
This PR fixes https://github.com/oagarcia/penguin-report/issues/11

### CODE REVIEW

**Comment by oagarcia** [comment]
@andreszorro @zorrodg , could you please confirm that your changes are merged with the last commits on feb-18? Those are related to closed https://github.com/oagarcia/penguin-report/issues/3
1299cd8a2ed4b718532832263a94e5defd4b48f6
2a3ed70fbbe9c120c4a1528c15d874693a878d57
198a9726ae50a9f590c89650a4e06b711de965d0

**Comment by andreszorro** [comment]
Seems so. Commit diffs show latest code, and PR shows no conflicts.

**Comment by oagarcia** [comment]
Tested locally and get the following error when trying to use notify feature:

`/Users/andresgarcia/Sites/penguin-basecamp-report/build/index.js:150`
`response.status(200).send(body);`
`ReferenceError: response is not defined`

**Comment by oagarcia** [comment]
tested, approved and merged... thanks!!!

**Pull request merged**
